//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaCarvajal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEvents
    {
        public int IdRecord { get; set; }
        public string Message { get; set; }
        public string Level { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string Exception { get; set; }
        public string Properties { get; set; }
        public string Modulo { get; set; }
        public string Metodo { get; set; }
        public string Error { get; set; }
    }
}
